version: '3.7'

services:
  ts-express-app:
    container_name: ts-express-app-prod
    build:
      context: .
      target: production
    image: ts-express-app-prod
    ports:
      - 3000:3000
    command: yarn start
