version: '3.7'

services:
  docker-test:
    container_name: docker-test-dev
    build:
      context: .
      target: base
    image: docker-test-dev
    expose:
      - "9229"
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./src:/src
    command: yarn dev
