version: '3.7'

services:
  ts-express-app:
    container_name: ts-express-app-dev
    build:
      context: .
      target: base
    image: ts-express-app-dev
    expose:
      - "9229"
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./src:/src
    command: yarn dev
